CREATE TABLE IF NOT EXISTS pedidos (
  id CHAR(36) NOT NULL PRIMARY KEY,
  numero BIGINT UNSIGNED NOT NULL,
  usuario_id BIGINT UNSIGNED NOT NULL,
  carrito_id CHAR(36) NOT NULL,
  clave_confirmacion CHAR(36) NOT NULL,
  estado ENUM('pendiente_revision','esperando_pago','cerrado','cancelado') NOT NULL DEFAULT 'pendiente_revision',
  productos JSON NOT NULL,
  entrega BIGINT UNSIGNED NULL,
  modalidad_entrega ENUM('retiro','envio') NOT NULL DEFAULT 'retiro',
  telefono_entrega VARCHAR(30) NOT NULL DEFAULT '',
  observaciones_entrega TEXT NULL,
  ajustes JSON NULL,
  subtotal_venta DECIMAL(14,2) NOT NULL,
  subtotal_costo DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_venta DECIMAL(14,2) NULL,
  total_costo DECIMAL(14,2) NOT NULL DEFAULT 0,
  creado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pedido_numero (numero),
  CONSTRAINT fk_pedidos_entrega FOREIGN KEY (entrega) REFERENCES usuarios_direcciones(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  UNIQUE KEY uq_pedido_carrito (carrito_id),
  UNIQUE KEY uq_pedido_confirmacion (usuario_id, clave_confirmacion),
  KEY idx_pedido_usuario (usuario_id, creado),
  KEY idx_pedido_estado (estado, creado)
) ENGINE=InnoDB;
